ls: cannot access /home/panwei/he000176/jinwen/gln/model_output/real/0.5/saved_models: No such file or directory
eirpredict --global_configs "/home/panwei/he000176/jinwen/gln/configs/base/real/global_config_0.5.yaml" --input_configs "/home/panwei/he000176/jinwen/gln/configs/ensemble/input_config.yaml" --output_configs "/home/panwei/he000176/jinwen/gln/configs/ensemble/output_config.yaml" --model_path "/home/panwei/he000176/jinwen/gln/model_output/real/0.5/saved_models/" --evaluate --output_folder "/home/panwei/he000176/jinwen/results/gln/ensemble/real/0.5"
13:19:32 - INFO - eir.train_utils.utils - Global random seed set to 0.
Traceback (most recent call last):
  File "/home/panwei/he000176/.conda/envs/eir-gln/bin/eirpredict", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/panwei/he000176/.conda/envs/eir-gln/lib/python3.11/site-packages/eir/predict.py", line 104, in main
    run_folder = get_run_folder_from_model_path(model_path=predict_cl_args.model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panwei/he000176/.conda/envs/eir-gln/lib/python3.11/site-packages/eir/experiment_io/experiment_io.py", line 39, in get_run_folder_from_model_path
    assert model_path_object.exists()
AssertionError
